# Generated by Django 4.2.1 on 2023-05-13 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_education',
            field=models.DateField(null=True, verbose_name='дата выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_education',
            field=models.DateField(default=datetime.date.today, verbose_name='начало обучения'),
        ),
    ]
