# Generated by Django 4.2.1 on 2023-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_end_education_alter_user_start_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='средний балл'),
        ),
    ]
