# Generated by Django 4.2.1 on 2023-05-13 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
        ('authentication', '0003_alter_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_education',
            field=models.DateField(null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_education',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало обучения'),
        ),
    ]
