# Generated by Django 4.2.1 on 2023-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_image',
            field=models.ImageField(default=False, upload_to='user_image', verbose_name='Фото пользователя'),
        ),
    ]
