# Generated by Django 4.2.1 on 2023-05-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='event_covers', verbose_name='Обложка новости')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tagline', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
