# Generated by Django 4.2.1 on 2023-05-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='news_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='новость'),
            preserve_default=False,
        ),
    ]
