# Generated by Django 4.2.1 on 2023-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(default=None, max_length=255, verbose_name='Описание фотографии'),
        ),
    ]
