# Generated by Django 4.2.1 on 2023-05-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_news_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='photo_gallery',
        ),
    ]
