# Generated by Django 4.2.1 on 2023-06-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_alter_visit_get_params_alter_visit_os_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='os',
        ),
    ]
