- hosts: all
  vars_prompt:
    - name: username
      prompt: What is your username (auth.yaml)?
      private: false
  remote_user: "{{ username }}"

  tasks:
    - name: Export user variable (playbook)
      set_fact:
        login_user: "{{ username }}"
      delegate_to: "{{ inventory_hostname }}"
      delegate_facts: yes

    - name: Print user variable (auth.yaml)
      debug:
        msg: "(auth.yaml) variable {{ login_user }}"

    - name: Check if connection is possible
      command: "ssh -o User={{ username }} -o ConnectTimeout=10 -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes {{ inventory_hostname }} echo 'Worked'"
      register: ssh_auth_result
      connection: local
      ignore_errors: yes
      changed_when: False

    - name: Prompt for SSH password if authentication failed
      ansible.builtin.pause:
        prompt: What is your password?
        private: true
      when: ssh_auth_result is failed
      register: ssh_password_input

    - name: Set SSH username and password if authentication failed
      set_fact:
        ansible_ssh_user: "{{ username }}"
        ansible_ssh_pass: "{{ ssh_password_input }}"
      when: ssh_auth_result is failed
