---
- hosts: all
  remote_user: "{{ login_user }}"
  vars:
    ansible_connection: ssh
    domain_name: our-school.space

  tasks:
    - name: Print user variable
      debug:
        var: login_user

    - name: Copy GitHub repo to /var/www
      git:
        repo: https://github.com/web-polytech/2023.git
        dest: /var/www/our-school
        version: max/infra-setup
        update: yes
    - name: Setup repo
      file:
        src: /var/www/our-school/nginx.conf
        dest: /etc/nginx/conf.d/our-school.conf
        state: link
      notify: Restart nginx
    - name: Generate SSL certificate for our-school.space
      shell: certbot --nginx --agree-tos --redirect --non-interactive --email wtf403@yandex.ru --domains {{ domain_name }}}

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  pre_tasks:
    - name: Install dependencies for deploy
      apt:
        name:
          - python3-certbot-nginx
          - git
        state: present
