---
- hosts: all
  remote_user: root
  vars:
    # brew install esolitos/ipa/sshpass
    ansible_connection: ssh

  vars_prompt:
    - name: new_username
      prompt: "Enter new user name"
      private: true

    - name: new_password
      prompt: "Enter new user password"
      private: true

  tasks:
    - name: Add new user
      user:
        name: "{{ new_username }}"
        password: "{{ new_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        groups: sudo
        append: yes

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: polytech
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Restrict root login and password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: "PermitRootLogin", line: "PermitRootLogin no" }
        - {
            regexp: "PasswordAuthentication",
            line: "PasswordAuthentication no",
          }
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

- import_playbook: auth.yaml
