# Generated by Django 4.2.1 on 2023-05-13 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='news_covers', verbose_name='Обложка новости')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tagline', models.CharField(max_length=255, verbose_name='Категория')),
                ('lid', models.TextField(verbose_name='Лид')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность чтения')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
