name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: cd frontend && npm ci && npm run build
      # Deploy
      - run: rsync --archive --compress --delete --exclude=.git/ --exclude=env/ --exclude=venv/ --exclude=node_modules/ . root@${{ vars.SERVER_IP }}:/var/www/our-school/
