name: Pylint checker

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install pylint
      - run: pylint .
